import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import { Navigation } from 'pages/app/ui/Navigation/Navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navClassName = "bg-amber-50 p-2 rounded hover:bg-amber-200";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navigation navLinks={[
          { href: "/",name: 'Home'  },
          { href: "/dashboard",name: 'Dashboard'  },
          { href: "/users",name: 'Users'  }
      ]} />
      <div className="p-3">
          {children}
      </div>
      </body>
    </html>
  )
}
